services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      # : -default => default value
      POSTGRES_USER: ${DB_USER:-james}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123}
      POSTGRES_DB: ${DB_NAME:-james_db}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#docker compose -f compose.yml up -d