#spring.application.name=restful_api_product_spring_boot

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update         # create | update | none
    show-sql: true              # log generated SQL
    properties:
      hibernate:
        format_sql: true
