#check docker compose configuration
#docker compose config
#docker compose up -d

volumes:
  ite-postgres-db-vol:
  ite-keycloak-vol:
networks:
  ite-net:
  # external: true

services:
  ite-postgres-db:
    image: postgres:18.4
    container_name: ite-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ite-postgres-db-vol:/var/lib/postgresql/18/docker
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ite-net
    restart: unless-stopped
  ite-keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    container_name: ite-keycloak
    environment:
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ite-postgres-db:5432/keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      # Admin User
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      # Production Settings
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT: false               # set to true if HTTPS
      KC_HOSTNAME_STRICT_HTTPS: false         # set to true if HTTPS
      KC_HOSTNAME_URL: http://${KC_HOSTNAME}:${KC_HOSTNAME_PORT}
      KC_HOSTNAME_ADMIN_URL: http://${KC_HOSTNAME}:${KC_HOSTNAME_PORT}
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      #KC_HTTPS_PORT: 443
      KC_PROXY_HEADERS: xforwarded
      KC_CACHE: ispn
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      JAVA_OPTS_APPEND: "-Xms512m -Xmx2048m"
    command: start               # use in production mode
    #command: start-dev                        # use in development mode
    ports:
      - "127.0.0.1:9999:8080"
    volumes:
      - ite-keycloak-vol:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/conf:/opt/keycloak/conf
    networks:
      - ite-net
    depends_on:
      - ite-postgres-db
    restart: unless-stopped